{
 "title": "Ceph LOC Visualizations",
 "description": "Dashboard for how LOC affect ceph build times",
 "time": { "from": "2014-07-02T15:26:43.000Z", "to": "2021-07-20T09:12:57.000Z" },
 "panels": [
  {
   "title": "LOC (C++), build duration over time",
   "type": "timeseries",
   "description": "shows lines of code (C++) and build duration for the Ceph project",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info as build_info\ninner join public.loc_data as loc_data\n  on loc_data.loc_version = build_info.ceph_version;\n"
    }
   ]
  },
  {
   "title": "LOC, Duration over time (16.x)",
   "type": "timeseries",
   "description": "Shows LOC and build duration over time for ceph versions 16.x",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '16.%';\n"
    }
   ]
  },
  {
   "title": "LOC (C++), Duration over time (16.x)",
   "type": "timeseries",
   "description": "Shows LOC (C++) and build duration over time for ceph versions 16.x",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '16.%';\n"
    }
   ]
  },
  {
   "title": "LOC, Duration over time (14.x)",
   "type": "timeseries",
   "description": "Shows LOC and build duration over time for ceph versions 14.x",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '14.%';\n"
    }
   ]
  },
  {
   "title": "LOC (C++), Duration over time (14.x)",
   "type": "timeseries",
   "description": "Shows lines of code (C++) and build durations over time for ceph versions 14.x",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '14.%';\n"
    }
   ]
  },
  {
   "title": "loc_data table",
   "type": "table",
   "description": "table showing data in loc_data table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.loc_data;\n"
    }
   ]
  },
  {
   "title": "LOC, Duration over time (14.x)",
   "type": "timeseries",
   "description": "Shows lines of code and build durations over time for ceph versions 14.x",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '14.%';\n"
    }
   ]
  },
  {
   "title": "LOC, build duration over time (all versions)",
   "type": "timeseries",
   "description": "shows lines of code and build duration for the Ceph project",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info as build_info\ninner join public.loc_data as loc_data\n  on loc_data.loc_version = build_info.ceph_version;\n"
    }
   ]
  },
  {
   "title": "LOC by version",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.loc_data;\n"
    }
   ]
  },
  {
   "title": "ceph_build_info table",
   "type": "table",
   "description": "shows data in babar's ceph_build_info table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info;\n"
    }
   ]
  }
 ]
}