{
 "title": "loc (python, c, java)",
 "time": { "from": "2020-09-15T04:00:00.000Z", "to": "2021-07-20T04:00:00.000Z" },
 "panels": [
  {
   "title": "LOC (Python) duration (v. 14.x)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '14.%';\n"
    }
   ]
  },
  {
   "title": "LOC duration (v. 16.x)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '16.%';\n"
    }
   ]
  },
  {
   "title": "LOC (C) duration (v. 14.x)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '14.%';\n"
    }
   ]
  },
  {
   "title": "LOC (Python) duration (v. 16.x)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '16.%';\n"
    }
   ]
  },
  {
   "title": "LOC, build duration over time (all versions)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info as build_info\ninner join public.loc_data as loc_data\n  on loc_data.loc_version = build_info.ceph_version;\n"
    }
   ]
  },
  {
   "title": "LOC (Java) duration (v. 14.x)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '14.%';\n"
    }
   ]
  },
  {
   "title": "LOC duration (v. 14.x)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '14.%';\n"
    }
   ]
  },
  {
   "title": "LOC (C) duration (v. 16.x)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.ceph_build_info\ninner join public.loc_data\n  on public.ceph_build_info.ceph_version = public.loc_data.loc_version\nwhere public.loc_data.loc_version like '16.%';\n"
    }
   ]
  }
 ]
}