{
 "title": "Rory's Shaman Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.builds\nwhere\n  status = 'completed' and\n  started > '2021-06-01' and\n  project_id != 11\nlimit 2500;\n"
    }
   ]
  },
  {
   "title": "Completed Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM \n  builds\nWHERE\n  status = 'completed' and\n  started >= '2021-01-01 00:00:00'\n;"
    }
   ]
  },
  {
   "title": "Build Duration vs Architecture",
   "type": "barchart",
   "description": "includes all build architectures",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.builds\nwhere\n  status = 'completed'\nlimit 5000\n;\n"
    }
   ]
  },
  {
   "title": "Duration by Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select\n  *\nfrom\n  public.builds\nwhere\n  status = 'completed' and\n  started > '2021-06-01 00:00:00'\n  \n"
    }
   ]
  }
 ]
}