{
 "title": "teiid",
 "description": "downstream build db for ceph",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "build_time_log",
   "type": "graph",
   "description": "General build logs that contains brew.build info (all tasks submitted to brew in the past 6 months)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "build time" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  brew.build.*,brew.events.time\n  AS creation_time\nFROM brew.build\nINNER JOIN brew.events ON brew.build.create_event=brew.events.id\nWHERE\n  brew.build.pkg_id = 34590 AND\n  brew.build.state  = 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "table_view",
   "type": "table",
   "description": "Table collection of all build time data from brew.build db.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  brew.build.*,brew.events.time\n  AS creation_time\nFROM brew.build\nINNER JOIN brew.events ON brew.build.create_event=brew.events.id\nWHERE\n  brew.build.pkg_id = 34590 AND\n  brew.build.state  = 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "arcs_mean_buildtime",
   "type": "barchart",
   "description": "Mean build time for each arch of all the build tasks submitted to brew).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  brew.task.id, arch, parent, state, start_time, completion_time\nFROM brew.task\nWHERE\n  (brew.task.state  = 1 or brew.task.state = 2 ) and\n  brew.task.owner = 3595 and brew.task.parent is not null\nORDER BY 1"
    }
   ]
  },
  {
   "title": "build_time_mean (by version)",
   "type": "barchart",
   "description": "Distribution of build time by version.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  brew.build.*,brew.events.time\n  AS creation_time\nFROM brew.build\nINNER JOIN brew.events ON brew.build.create_event=brew.events.id\nWHERE\n  brew.build.pkg_id = 34590 AND\n  brew.build.state  = 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "file_size_arch (16.2.0)",
   "type": "barchart",
   "description": "File size by arc for version 16.2.0. Used to visualize the file sizes being submitted to each arc.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,arch,rpminfo.size\nFROM\n  rpminfo\nWHERE\n  version = '16.2.0';"
    }
   ]
  },
  {
   "title": "src_size (version)",
   "type": "barchart",
   "description": "Distribution of source file sizes by version.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  version,size,buildtime\nFROM\n  rpminfo\nWHERE\n  name = 'ceph' and arch = 'src' and version > '10.1.0';\n"
    }
   ]
  },
  {
   "title": "file_size (16.2.4)",
   "type": "barchart",
   "description": "Distribution of file sizes (avg) that belongs to all builds from version 16.2.4.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,rpminfo.size\nFROM\n  rpminfo\nWHERE\n  version = '16.2.4';"
    }
   ]
  },
  {
   "title": "file_size (16.2.0)",
   "type": "barchart",
   "description": "Distribution of file sizes (avg) that belongs to all builds from version 16.2.0.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  name,rpminfo.size\nFROM\n  rpminfo\nWHERE\n  version = '16.2.0';\n"
    }
   ]
  }
 ]
}